# Generated by Django 5.0.1 on 2024-10-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('uuid', models.UUIDField(unique=True)),
            ],
        ),
    ]
