# Generated by Django 5.0.1 on 2024-10-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
